"""Initial kernel schema.

Creates the 13 kernel tables registered on `orchestra_core.db.meta`:

- project, project_version
- context, context_counter, context_version
- log_event, log_event_context, log_event_version
- active_derived_log_template, log_unique_constraint
- field_type
- embedding, embedding_queue

Uses the SQLAlchemy metadata directly so the migration stays in sync with
the model definitions without a hand-maintained DDL block. The kernel's
alembic env (orchestra_core/db/migrations/env.py) loads only the kernel
model package, so `meta.create_all()` here creates exactly the kernel
tables and nothing else.

Revision ID: 0001_core_initial
Revises:
Create Date: 2026-05-22 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa  # noqa: F401  (used by autogenerated future migrations)

revision = "0001_core_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()

    # Required for the embedding/embedding_queue Vector columns.
    bind.exec_driver_sql("CREATE EXTENSION IF NOT EXISTS vector")

    from orchestra_core.db.meta import meta
    from orchestra_core.db.models import load_all_models

    load_all_models()
    meta.create_all(bind=bind, checkfirst=True)


def downgrade() -> None:
    bind = op.get_bind()
    from orchestra_core.db.meta import meta
    from orchestra_core.db.models import load_all_models

    load_all_models()
    meta.drop_all(bind=bind, checkfirst=True)
